sudo: false
language: go
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -bench -race -v ./...
after_success:
$HOME/gopath/bin/goveralls -service=travis-ci
